### PR TITLE
Clip ripple effect to existing message box borders

### PR DESCRIPTION
**Pull request by Bloemcol**

### CODE REVIEW

**Comment by ehoogend** [comment]
Hi @Bloemcol, thanks for the PR. We'll discuss the changes with the designers and merge them into the private repository if they're approved. Once the changes are in master they'll be pushed to the public Github repo as well.

**Comment by ehoogend** [comment]
@Bloemcol For your commits to be accepted, please ensure your commits are signed and verified by Github. (See [here](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification) for more info)

**Comment by Bloemcol** [comment]
@ehoogend Thanks for the heads-up! Will do that shortly.

**Comment by Bloemcol** [comment]
After some signing issues, please check #58 for signed and verified commits.

**Pull request closed without merging**
