### PR TITLE
Update Gradle Wrapper from 6.7 to 6.8

### PR DESCRIPTION
**Pull request by EwoutH**
Succeeds #42, and now done properly:
 - Check of the Sha-256 hash added
 - Updated gradlew and gradlew.bat scripts
 - Updated the gradle-wrapper.jar (which executes the download of the correct Gradle version)

> Update Gradle Wrapper from 6.7 to 6.8.
> 
> Read the release notes: https://docs.gradle.org/6.8/release-notes.html
> 
> ---
> 
> The checksums of the Wrapper JAR and the distribution binary have been successfully verified.
> 
> - Gradle release: `6.8`
> - Distribution (-bin) zip checksum: `e2774e6fb77c43657decde25542dea710aafd78c4022d19b196e7e78d79d8c6c`
> - Wrapper JAR Checksum: `e996d452d2645e70c01c11143ca2d3742734a28da2bf61f25c82bdc288c9e637`
> 
> You can find the reference checksum values at https://gradle.org/release-checksums/
> 
> ---
> 
> 🤖 This PR has been created by the [Update Gradle Wrapper](https://github.com/gradle-update/update-gradle-wrapper-action) action.

### CODE REVIEW

**Comment by lpappalettera** [comment]
Thanks @EwoutH, can you sign the commit?

**Comment by EwoutH** [comment]
Done!

**Comment by EwoutH** [comment]
Thanks for merging. I could add a quick CI script that checks once a week if a new Gradle version is available, and if so, opens a PR similar to this. Would you find that usefull?

**Comment by lpappalettera** [comment]
@EwoutH sounds good to me :)

**Comment by EwoutH** [comment]
Great, opened a PR here: #55

**Pull request merged**
