### PR TITLE
Fix missing whitespace in lab_test_paragraph_1

### PR DESCRIPTION
**Pull request by tschut**
Noticed a missing whitespace.

### CODE REVIEW

**Comment by hvisser** [comment]
Thanks for the PR! We sync translations from our translation management system and I've made the change there, so next time we sync the space is added. I'll keep this open until we have.

**Comment by tschut** [comment]
Thanks @hvisser. Is there a better place to make contributions like this in the future?

**Comment by hvisser** [comment]
@tschut I don't think we have a better way at the moment. From the perspective of development it's not something we manage really, even though it's "code" in our repository. Filing an issue or a PR like this would still be the best way to contribute.

**Comment by hvisser** [comment]
This has now been fixed on master, thanks again for your contribution!

**Pull request closed without merging**
